# Generated by Django 5.0.6 on 2024-08-15 23:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="posts",
        ),
    ]
